# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8099
  servlet:
    # 应用访问路径
    context-path: /pat
  tomcat:
    additional-tld-skip-patterns: jaxb-api.jar,jaxb-core.jar
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 1000
    # tomcat启动初始化线程数，默认为25
    min-spare-threads: 30

# 日志配置
logging:
  path: /Users/alisha/IdeaProjects/pat/logs
  level:
    org.sprinframework: warn
    com.fasterxml.jackson: INFO
    com.pat.pmp: DEBUG

# Spring 配置
spring:
  profiles:
    active: druid
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 100MB
      # 设置总文件上传大小
      max-request-size: 100MB
      enabled: true
      # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 10s
    lettuce:
      pool:
        # 连接池中最小空闲连接
        min-idle: 0
        # 连接池中最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
  freemarker:
    cache: false
    suffix: .html
    request-context-attribute: request
    template-loader-path: classpath:/templates
  # datasource 配置
#  datasource:
#    initialization-mode: never
#    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://127.0.0.1:3306/pmp?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
#      username: root
#      password: zfy123456
#      # 初始化连接池数量
#      initial-size: 10
#      # 最大连接池数量
#      max-active: 50
#      # 最小连接池数量
#      min-idle: 10
#      # 配置链接等待超时的时间
#      max-wait: 60000
#      pool-prepared-statements: true
#      max-pool-prepared-statement-per-connection-size: 20
#      # 配置多久才进行一次检测，检测需要关闭空闲连接，单位是毫秒
#      time-between-eviction-runs-millis: 60000
#      # 配置一个连接在池中最小生存的时间，单位是毫秒
#      min-evictable-idle-time-millis: 300000
#      # 配置一个连接在池中最大生存的时间，单位是毫秒
#      max-evictable-idle-time-millis: 900000
#      validation-query: SELECT 1 FROM DUAL
#      test-while-idle: true
#      test-on-borrow: false
#      test-on-return: false
#      stat-view-servlet:
#        enabled: true
#        url-pattern: /druid/*
#        # 设置白名单，不填则允许所有访问
#        allow:
#      filter:
#        stat:
#          # 慢查询记录
#          log-slow-sql: true
#          slow-sql-millis: 1000
#          merge-sql: true
#          enabled: true
#        wall:
#          config:
#            multi-statement-allow: true
  jmx:
    enabled: false

redis:
  config:
    host: redis:/127.0.0.1:6379



# mybatis 配置
mybatis-plus:
  # 配置mapper的扫描，找到所有的*mapper.xml文件
  mapper-locations: classpath:mappers/*.xml
  # 搜索指定包别名
  type-aliases-package: com.pat.pmp.model.entity
  global-config:
    banner: false
    db-config:
      id-type: auto
      field-strategy: not_null
      column-underline: true
      logic-delete-value: -1
      logic-not-delete-value: 0
